import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from '../components/ui/theme-provider';
import NavBar from '../components/NavBar';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={` antialiased`}
      >
      <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange
    >
<main className="container mx-auto">
    <NavBar></NavBar>
      {children}
</main>
    </ThemeProvider>
      </body>
    </html>
  );
}
